/*
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.
Source: https://projecteuler.net/problem=2 
*/

#include <stdio.h>

#define MAX 50
#define HIGHEST_VAL 4000000

int main(void) {

    unsigned long fib[MAX] = {0}; // store fibonacci sequence in an array
    // set the first two numbers to be 1
    fib[0] = 1; 
    fib[1] = 1;

    int i = 2;
    unsigned long sum = 0;
    int stop = 0;
    // while the value does not exceed 4 million
    while (stop == 0) {
        if ((fib[i-2] + fib[i-1]) < HIGHEST_VAL) {
            fib[i] = fib[i-2] + fib[i-1]; // next is sum of previous two
            if (fib[i] % 2 == 0) { // if the number is even
                sum += fib[i]; // add it to the sum
            }
        } else {
            stop = 1;
        }
        i++;
    }

    printf("%lu\n", sum);
    return 0;
}